---
- name: Create a container
  docker_container:
    name: Casestudy-Spring-Boot
    image: "{{ docker_image }}"
    ports:
    - "8080:8888"
  when:
    - ansible_connection != "docker"

- debug: msg="http://{{ inventory_hostname }}:8080 is URL for your application."
