---
- import_playbook: playbooks/gcp_instance_creation.yml

- import_playbook: playbooks/gcp_docker_installation.yml
  tags:
  - create

- import_playbook: playbooks/gcp_docker_run.yml
  tags:
  - create
